#ifndef RASTRMANIPULATIONLIBRARY_GLOBAL_H
#define RASTRMANIPULATIONLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RASTRMANIPULATIONLIBRARY_LIBRARY)
#  define RASTRMANIPULATIONLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RASTRMANIPULATIONLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RASTRMANIPULATIONLIBRARY_GLOBAL_H
